sudo: false

notifications:
  email: false

os: osx

matrix:
  include:
    - language: swift
      name: "Cocoapods BlueprintUI (Xcode 10.2)"
      xcode_scheme: BlueprintUI-Unit-Tests
      osx_image: xcode10.2
      xcode_workspace: SampleApp.xcworkspace
      xcode_destination: platform=iOS Simulator,OS=9.3,name=iPhone 4s
      before_install:
        - cd SampleApp
        - bundle install
        - bundle exec pod repo update
        - bundle exec pod install

    - language: swift
      name: "SPM (Xcode 11.2)"
      os: osx
      osx_image: xcode11.2
      script:
        # Split into two commands so that we can pass 'quiet' during build to only see errors and warnings.
        - xcodebuild build-for-testing -quiet -scheme "BlueprintUI-Package" -destination "name=iPad Pro (9.7-inch)"
        - xcodebuild test-without-building -scheme "BlueprintUI-Package" -destination "name=iPad Pro (9.7-inch)"

