sudo: false

notifications:
  email: false

matrix:
  include:
    - language: swift
      name: "Xcode 10.2"
      os: osx
      osx_image: xcode10.2
      xcode_workspace: SampleApp.xcworkspace
      xcode_scheme: 
        - BlueprintUI-Unit-Tests
        - BlueprintUICommonControls-Unit-SnapshotTests
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPad Pro (9.7-inch)
      before_install:
        - gem update --system
        - gem install bundler
        - bundle install
        - bundle exec pod repo update
        - bundle exec pod install
 
